[package]
name = "nauty-bindgen"
version = "0.1.0"
authors = ["Andreas Maier <andreas.martin.maier@desy.de>"]
edition = "2018"

[build-dependencies]
bindgen = "0.53"

[dependencies]
env_logger = "0.7"
num-integer = "0.1"
