#include "src/nauty2_8_9/nauty.h"
#include "src/nauty2_8_9/naugroup.h"
#include "src/nauty2_8_9/nausparse.h"
#include "src/nauty2_8_9/nautinv.h"
#include "src/nauty2_8_9/traces.h"
#include "src/nauty2_8_9/gutils.h"
