#include "src/nauty2_8_8/nauty.h"
#include "src/nauty2_8_8/naugroup.h"
#include "src/nauty2_8_8/nausparse.h"
#include "src/nauty2_8_8/nautinv.h"
#include "src/nauty2_8_8/traces.h"
#include "src/nauty2_8_8/gutils.h"
